// <auto-generated />
using System;
using App.Volvo.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Volvo.Data.Migrations
{
    [DbContext(typeof(AppVolvoDbContext))]
    partial class AppVolvoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Volvo.Business.Models.Caminhao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("AnoFabricacao")
                        .HasColumnType("smallint");

                    b.Property<short>("AnoModelo")
                        .HasColumnType("smallint");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("varchar(17)");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Caminhoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("922e05b8-fb2f-4c41-8e7a-0b09a6d07a2f"),
                            AnoFabricacao = (short)2021,
                            AnoModelo = (short)2021,
                            Chassi = "398A4ch95b9PX8897",
                            ModeloId = new Guid("c2482af3-101e-4e7f-9db0-727169994fb3")
                        });
                });

            modelBuilder.Entity("App.Volvo.Business.Models.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPermitidoCadastro")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Modelos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2482af3-101e-4e7f-9db0-727169994fb3"),
                            IsPermitidoCadastro = true,
                            Nome = "FH"
                        },
                        new
                        {
                            Id = new Guid("f67b0e15-68f9-4528-b546-de09d0034bef"),
                            IsPermitidoCadastro = true,
                            Nome = "FM"
                        },
                        new
                        {
                            Id = new Guid("d6f57506-96b4-4422-946e-5bdf2103ee2a"),
                            IsPermitidoCadastro = false,
                            Nome = "FMX"
                        },
                        new
                        {
                            Id = new Guid("03b7333a-3aa0-48c3-85d5-a72279cde5d5"),
                            IsPermitidoCadastro = false,
                            Nome = "FHX"
                        });
                });

            modelBuilder.Entity("App.Volvo.Business.Models.Caminhao", b =>
                {
                    b.HasOne("App.Volvo.Business.Models.Modelo", "Modelo")
                        .WithMany("Caminhoes")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("App.Volvo.Business.Models.Modelo", b =>
                {
                    b.Navigation("Caminhoes");
                });
#pragma warning restore 612, 618
        }
    }
}
